### ISSUE TITLE
KMP: cinterop fails to find interface declaration for 'DDURLSessionDelegate'

### ISSUE THREAD

**Issue by maurycyw** [DataDog/dd-sdk-ios#402]
### cinterop fails for DatadogSDKObjc pod

Using the following in my kotlin multiplatform project (Kotlin 1.4.21):
```
pod(name = "DatadogSDKObjc", moduleName = "DatadogObjc", version = "~>1.5.0-alpha2")
```

cinterop is failing with the following:
```
Exception in thread "main" java.lang.Error: /.../common/build/cocoapods/synthetic/IOS/common/build/Release-iphonesimulator/DatadogSDKObjc/DatadogObjc.framework/Headers/DatadogObjc-Swift.h:965:37: error: cannot find interface declaration for 'DDURLSessionDelegate', superclass of 'DDNSURLSessionDelegate'
	at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:152)
	at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.indexDeclarations(Indexer.kt:1003)
	at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.buildNativeIndexImpl(Indexer.kt:992)
	at org.jetbrains.kotlin.native.interop.indexer.NativeIndexKt.buildNativeIndex(NativeIndex.kt:91)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:267)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:73)
	at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:45)
	at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:19)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:41)
```

I realized this might be a cinterop issue but it is actually not very clear. I created a YouTrack ticket as well here in case: https://youtrack.jetbrains.com/issue/KT-44724

**Comment by ncreated** [comment]
Hello @maurycyw 👋, thank you for reaching us. Unfortunately, I never used `cinterop` and we don't officially support it, but Iet me explain how `DDURLSessionDelegate` is architectured inside `DatadogSDKObjc` - I hope this may be helpful.

The `DatadogSDKObjc` module exposes Objc-interoperability APIs for all the features implemented in `DatadogSDK` module. The `DatadogSDKObjc` is not a stand-alone module: it has a strong dependency on the `DatadogSDK`, so it compiles and links it. In many places, `DatadogSDKObjc` acts as a simple "umbrella" on top of the `DatadogSDK` to forwards all the Obj-c calls (made to `DatadogObjcSDK`) to Swift (to `DatadogSDK`).

Now, speaking of `DDURLSessionDelegate` interface (from the error message) → it is defined in `DatadogSDK` and meant for Swift users of `DatadogSDK`. In `DatadogObjcSDK`, we define its objc-interoperability superclass: `DDNSURLSessionDelegate` as an umbrella type for Obj-c users.

Given that, I think your further investigation should be targeted at finding out if the `DatadogSDK` (Swift) module is properly linked and compiled in your resultant solution. Only then, the `DatadogObjcSDK` (Obj-c interop) will be able to see the necessary symbols and make it work.

Hope you will find this notes useful - let me know if we can help further 🙌.

**Comment by maurycy-yolabs** [comment]
thank you @ncreated for your response! We managed follow the workaround outlined in: https://youtrack.jetbrains.com/issue/KT-44724 to get things working (in case any one else runs into this issue).

**Comment by ncreated** [comment]
Thanks for the follow up @maurycy-yolabs - I'm happy it works for you 🙂! I'm closing this issue as it seems resolved (nothing to do on our side, and you link to clear instructions on how to configure `dd-sdk-ios` for `cinterop`).
